services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: portfolio
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - bridge-network

networks:
  bridge-network:
    external: true
